# Generated by Django 3.1.5 on 2021-02-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Manager',
            fields=[
                ('am_uid', models.AutoField(primary_key=True, serialize=False)),
                ('am_name', models.CharField(max_length=100)),
                ('am_email', models.CharField(max_length=100)),
                ('am_mobile', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'account_manager',
            },
        ),
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('company_ticker', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('exchange_type', models.CharField(max_length=25)),
                ('currency', models.CharField(max_length=5)),
                ('industry', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('isin', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('normalizer', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('am_uid', models.ForeignKey(db_column='am_uid', on_delete=django.db.models.deletion.CASCADE, to='company_api.account_manager')),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='Company_Quote',
            fields=[
                ('company_ticker', models.OneToOneField(db_column='company_ticker', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company_api.company_profile')),
                ('market_cap', models.FloatField()),
                ('price', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'company_quote',
            },
        ),
        migrations.CreateModel(
            name='Company_Trading',
            fields=[
                ('company_ticker', models.OneToOneField(db_column='company_ticker', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company_api.company_profile')),
                ('market_date', models.DateField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('vwap', models.FloatField()),
                ('volume', models.FloatField()),
                ('change_percent', models.FloatField()),
            ],
            options={
                'db_table': 'company_trading',
            },
        ),
    ]
